version: "3.4"

# Production environment override
services:
  php:
    image: ${IMAGES_PREFIX:-pkg.miris.design/miris/influenzai}/php:latest
    build:
      context: .
      target: php_prod
    volumes:
      - app_cache:/srv/app/bootstrap/cache
      - app_storage:/srv/app/storage
    environment:
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV:-production}
      APP_URL: ${APP_URL}

  caddy:
    image: ${IMAGES_PREFIX:-pkg.miris.design/miris/influenzai}/caddy:latest
    build:
      context: .
      target: caddy_prod

  api:
    image: ${IMAGES_PREFIX:-pkg.miris.design/miris/influenzai}/api:latest
    build:
      context: api
      target: builder

volumes:
  app_cache:
  app_storage:
