version: "3.4"

# Production environment override
services:
  php:
    build:
      context: .
      target: php_prod
    volumes:
      - app_cache:/srv/app/bootstrap/cache
      - app_storage:/srv/app/storage
    environment:
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV:-production}
      APP_URL: ${APP_URL}

  caddy:
    build:
      context: .
      target: caddy_prod

  api:
    build:
      context: api
      target: builder

volumes:
  app_cache:
  app_storage:
